-- Goal-event PROPERTIES: the payload a metric's value_field extracts from.
--
-- A sum/mean metric needs a numeric value per event. Two ways to provide it, and
-- we support BOTH (most flexible, and both are analysis-time / recompute-friendly):
--   1. Direct: the SDK sends `value` (unchanged) — experiment_metric_events.value.
--   2. Payload: the SDK sends `properties` (arbitrary JSON), and the metric's
--      `value_field` (a dot-path) extracts the number at ANALYSIS time. Because the
--      raw payload is stored, a metric whose value_field changes — or a NEW metric
--      over the same event — re-derives its value over full history, exactly like
--      the rest of the retroactive analysis model.
--
-- Nullable, no default: events without a payload just have null properties and fall
-- back to `value`. Tenant table already has its RLS policy from 0025.
ALTER TABLE "experiment_metric_events" ADD COLUMN "properties" jsonb;
