"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Button, Field, Input, Select, Textarea } from "@/components/form-controls";
import { SubmitButton } from "@/components/submit-button";
import type { CriteriaGroup, FlagType, TargetingRule, Variant } from "@/lib/flags";
import { CriteriaBuilder } from "./criteria-builder";

const newCriteria = (): CriteriaGroup => ({ operator: "all", items: [{ kind: "attribute", attribute: "", operator: "equals", valueType: "string", value: "" }] });
const displayName = (type: FlagType) => type === "object" ? "JSON object" : type[0].toUpperCase() + type.slice(1);
function equalRollout(variants: Variant[]) { const base = Math.floor(10000 / variants.length) / 100; let used = 0; return variants.map((variant, index) => { const weight = index === variants.length - 1 ? Number((100 - used).toFixed(2)) : base; used += weight; return { variant: variant.key, weight }; }); }
function ObjectValue({ value, onChange }: { value: unknown; onChange: (value: unknown) => void }) { const [draft, setDraft] = useState(() => JSON.stringify(value, null, 2)); const [invalid, setInvalid] = useState(false); return <div><Textarea value={draft} onChange={(event) => { const next = event.target.value; setDraft(next); try { onChange(JSON.parse(next)); setInvalid(false); } catch { setInvalid(true); } }} aria-invalid={invalid} className={`min-h-24 font-mono text-xs ${invalid ? "border-red-500/60 focus:border-red-500/60 focus:ring-red-500/20" : ""}`} />{invalid ? <p className="mt-1 text-xs text-red-400">Enter valid JSON.</p> : null}</div>; }
function VariantValue({ type, variant, onChange }: { type: FlagType; variant: Variant; onChange: (value: unknown) => void }) { if (type === "object") return <ObjectValue value={variant.value} onChange={onChange} />; if (type === "string") return <Input value={String(variant.value)} onChange={(event) => onChange(event.target.value)} placeholder="Value returned by evaluation" />; return <Input type="number" step={type === "integer" ? "1" : "any"} value={String(variant.value)} onChange={(event) => onChange(Number(event.target.value))} />; }

export function FlagDefinitionEditor({ action, flag, segments }: { action: (form: FormData) => void | Promise<void>; flag: { name: string; description: string | null; type: string; variants: Variant[]; defaultVariant: string; rules: TargetingRule[] }; segments: Array<{ key: string; name: string }> }) {
  const type = flag.type as FlagType; const boolean = type === "boolean"; const [variants, setVariants] = useState(flag.variants); const [rules, setRules] = useState(flag.rules);
  const label = (key: string) => boolean ? key === "on" ? "On" : "Off" : key;
  const variantOptions = variants.map((variant) => ({ value: variant.key, label: label(variant.key) }));
  const setRule = (index: number, rule: TargetingRule) => setRules((items) => items.map((item, itemIndex) => itemIndex === index ? rule : item));
  const moveRule = (index: number, offset: number) => setRules((items) => { const next = [...items]; const target = index + offset; [next[index], next[target]] = [next[target], next[index]]; return next; });
  return <form action={action} className="mt-8 grid gap-8"><input type="hidden" name="variants" value={JSON.stringify(variants)} /><input type="hidden" name="rules" value={JSON.stringify(rules)} />
    <section className="border border-white/10 bg-white/[0.02] p-4"><h2 className="text-sm font-semibold text-zinc-200">Details</h2><p className="mt-1 text-xs text-zinc-500">Give this flag a clear name and optional description for your team.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Name"><Input name="name" defaultValue={flag.name} /></Field><Field label="Description"><Input name="description" defaultValue={flag.description ?? ""} placeholder="What does this flag control?" /></Field></div></section>
    {!boolean ? <section><h2 className="text-sm font-semibold text-zinc-200">Values</h2><p className="mt-1 text-xs text-zinc-500">Create named {displayName(type).toLowerCase()} values that rules can serve.</p><div className="mt-4 space-y-3">{variants.map((variant, index) => <div key={index} className="grid items-start gap-3 border border-white/8 bg-white/[0.02] p-3 md:grid-cols-[220px_1fr_auto]"><Field label="Key"><Input value={variant.key} onChange={(event) => setVariants((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, key: event.target.value } : item))} className="font-mono" /></Field><Field label="Value"><VariantValue type={type} variant={variant} onChange={(value) => setVariants((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, value: value as never } : item))} /></Field><Button variant="ghost" size="sm" disabled={variants.length === 1} onClick={() => setVariants((items) => items.filter((_, itemIndex) => itemIndex !== index))} aria-label="Remove value" className="mt-6 px-2 hover:text-red-400"><Trash2 className="h-4 w-4" /></Button></div>)}</div><div className="mt-3 flex justify-end"><Button variant="secondary" size="sm" onClick={() => setVariants((items) => [...items, { key: `value-${items.length + 1}`, value: type === "string" ? "" : type === "object" ? {} : 0 }])} className="gap-1.5"><Plus className="h-3.5 w-3.5" /> Add value</Button></div></section> : null}
    <section><div className="flex items-end justify-between"><div><h2 className="text-sm font-semibold text-zinc-200">Evaluation behavior</h2><p className="mt-1 text-xs text-zinc-500">Add exceptions for specific users or contexts. Rules are checked from top to bottom, and the first match wins.</p></div><Button variant="secondary" size="sm" onClick={() => setRules((items) => [...items, { name: `Rule ${items.length + 1}`, criteria: newCriteria(), variant: variants[0]?.key }])} className="gap-1.5"><Plus className="h-3.5 w-3.5" /> Add targeting rule</Button></div>
      {!rules.length ? <div className="mt-4 border border-dashed border-white/10 bg-white/[0.015] px-5 py-6"><p className="text-sm font-medium text-zinc-300">Everyone currently receives {label(flag.defaultVariant)}.</p><p className="mt-1 text-xs text-zinc-500">There are no targeting exceptions. Add a rule to serve a different outcome to matching contexts.</p></div> : null}
      <div className="mt-4 space-y-4">{rules.map((rule, index) => <article key={index} className="border border-white/10 bg-white/[0.02] shadow-sm shadow-black/20"><header className="flex items-center gap-3 border-b border-white/8 bg-white/[0.025] px-4 py-3"><span className="rounded border border-teal-500/20 bg-teal-500/8 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-teal-400">{index === 0 ? "If" : "Else if"}</span><Input compact aria-label={`Rule ${index + 1} name`} value={rule.name ?? `Rule ${index + 1}`} onChange={(event) => setRule(index, { ...rule, name: event.target.value })} className="max-w-sm border-transparent bg-transparent px-2 font-medium hover:border-white/10 focus:bg-black/20" /><span className="text-[11px] text-zinc-600">Rule {index + 1}</span><Button variant="ghost" size="sm" disabled={index === 0} onClick={() => moveRule(index, -1)} aria-label="Move rule up" className="ml-auto px-2"><ArrowUp className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" disabled={index === rules.length - 1} onClick={() => moveRule(index, 1)} aria-label="Move rule down" className="px-2"><ArrowDown className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => setRules((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="px-2 hover:text-red-400" aria-label="Remove rule"><Trash2 className="h-4 w-4" /></Button></header><div className="p-4"><p className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-zinc-600">When</p><CriteriaBuilder value={rule.criteria} onChange={(criteria) => setRule(index, { ...rule, criteria })} segments={segments} /></div>
        <footer className="border-t border-white/8 bg-black/15 p-4"><div className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-zinc-600">Then</div><div className="flex flex-wrap items-end gap-3"><Field label="Serve outcome" className="min-w-48 flex-1">{rule.rollout ? <div className="flex h-8 items-center rounded-md border border-white/10 bg-black/10 px-3 text-xs text-zinc-400">Distributed by percentage</div> : <Select compact ariaLabel="Outcome to serve" value={rule.variant} onValueChange={(variant) => setRule(index, { ...rule, variant })} options={variantOptions} />}</Field><Field label="Delivery" className="w-52"><Select compact ariaLabel="Outcome delivery" value={rule.rollout ? "rollout" : "variant"} onValueChange={(outcome) => setRule(index, outcome === "rollout" ? { ...rule, rollout: equalRollout(variants) } : { ...rule, rollout: undefined, variant: variants[0]?.key })} options={[{ value: "variant", label: "Fixed outcome" }, { value: "rollout", label: "Percentage rollout" }]} /></Field></div>{rule.rollout ? <div className="mt-3 grid gap-2 rounded-md border border-white/7 bg-black/10 p-3 sm:grid-cols-2">{rule.rollout.map((split, splitIndex) => <Field key={split.variant} label={label(split.variant)}><div className="relative"><Input compact type="number" min="0" max="100" step="0.01" value={split.weight} onChange={(event) => setRule(index, { ...rule, rollout: rule.rollout?.map((item, itemIndex) => itemIndex === splitIndex ? { ...item, weight: Number(event.target.value) } : item) })} className="pr-8" /><span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs text-zinc-600">%</span></div></Field>)}</div> : null}</footer>
      </article>)}</div>
      <div className="mt-4 border border-white/10 bg-white/[0.02] p-4"><p className="text-sm font-medium text-zinc-300">Default outcome</p><p className="mt-1 text-xs text-zinc-500">If no targeting rule matches, serve this outcome.</p><div className="mt-3 max-w-xs"><Select ariaLabel="Default outcome" name="default_variant" defaultValue={flag.defaultVariant} options={variantOptions} /></div></div>
    </section><SubmitButton pendingLabel="Saving…" className="w-fit px-5">Save flag</SubmitButton>
  </form>;
}
